"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Bell, CalendarDays, Check, ChevronRight, CircleUserRound, Clock3, Edit3, Inbox, LayoutDashboard, Loader2, LogOut, Plus, Search, Sparkles, Target, Trash2, TrendingUp, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { Progress } from "@/components/ui/progress";
import { Textarea } from "@/components/ui/textarea";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";

type Task = { id:string; title:string; dueDate:string; dueTime:string|null; duration:number; priority:string; category:string; energy:string; repeat:string; guide:string; reminder:boolean|number; done:boolean|number; completedAt:string|null };
type Draft = Omit<Task,"id"|"done"|"completedAt">;
const emptyDraft=():Draft=>({title:"",dueDate:new Date().toISOString().slice(0,10),dueTime:"",duration:30,priority:"normal",category:"Trabalho",energy:"medium",repeat:"none",guide:"",reminder:true});
const ptDate=(date:string)=>new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short"}).format(new Date(date+"T12:00:00"));
const isOverdue=(t:Task)=>!t.done&&new Date(`${t.dueDate}T${t.dueTime||"23:59"}:00`)<new Date();
const tipFor=(title:string,category:string)=>{const s=title.toLowerCase();if(s.includes("organizar"))return "Separe em três grupos: resolver, guardar e descartar. Comece pelo menor.";if(s.includes("pagar"))return "Confirme o vencimento, abra o banco e salve o comprovante.";if(category==="Estudo")return "Escolha um assunto pequeno e faça uma sessão curta sem distrações.";if(category==="Saúde")return "Prepare o necessário primeiro e comece com uma versão simples.";return "Comece pela menor ação concreta que deixe esta tarefa mais próxima do fim."};

export default function FlowApp({user}:{user:{name:string;email:string}}){
  const [tasks,setTasks]=useState<Task[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
  const [view,setView]=useState("today");const [modal,setModal]=useState(false);const [editing,setEditing]=useState<string|null>(null);const [draft,setDraft]=useState<Draft>(emptyDraft());const [search,setSearch]=useState("");const [filter,setFilter]=useState("all");
  const today=new Date().toISOString().slice(0,10);
  async function load(){setLoading(true);try{const r=await fetch("/api/tasks",{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error);setTasks(d.tasks)}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível sincronizar") }finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const todayTasks=useMemo(()=>tasks.filter(t=>(t.dueDate===today||isOverdue(t))&&!t.done).filter(t=>{const q=(t.title+" "+t.category).toLowerCase();return(!search||q.includes(search.toLowerCase()))&&(filter==="all"||(filter==="urgent"&&t.priority==="urgent")||(filter==="overdue"&&isOverdue(t))||(filter==="quick"&&t.duration<=20))}),[tasks,today,search,filter]);
  const doneToday=tasks.filter(t=>t.done&&t.completedAt?.slice(0,10)===today);const pct=todayTasks.length+doneToday.length?Math.round(doneToday.length/(todayTasks.length+doneToday.length)*100):0;
  async function request(method:string,body?:unknown,url="/api/tasks"){const r=await fetch(url,{method,headers:{"content-type":"application/json"},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
  async function saveTask(){if(!draft.title.trim())return toast.error("Informe o nome da tarefa");setSaving(true);try{editing?await request("PATCH",{id:editing,...draft}):await request("POST",draft);toast.success(editing?"Alterações sincronizadas":"Afazer adicionado à rota");setModal(false);setEditing(null);setDraft(emptyDraft());await load()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar")}finally{setSaving(false)}}
  function edit(t:Task){setEditing(t.id);setDraft({title:t.title,dueDate:t.dueDate,dueTime:t.dueTime||"",duration:t.duration,priority:t.priority,category:t.category,energy:t.energy,repeat:t.repeat,guide:t.guide,reminder:Boolean(t.reminder)});setModal(true)}
  async function toggle(t:Task){try{await request("PATCH",{id:t.id,done:!t.done});setTasks(x=>x.map(v=>v.id===t.id?{...v,done:!t.done,completedAt:!t.done?new Date().toISOString():null}:v));toast.success(!t.done?"Boa! Tarefa concluída.":"Tarefa reaberta.");if(!t.done&&t.repeat!=="none")setTimeout(load,400)}catch(e){toast.error("Não foi possível atualizar")}}
  async function remove(id:string){try{await request("DELETE",undefined,`/api/tasks?id=${id}`);setTasks(x=>x.filter(t=>t.id!==id));toast.success("Afazer removido") }catch{toast.error("Não foi possível remover")}}
  async function tomorrow(t:Task){const d=new Date();d.setDate(d.getDate()+1);try{await request("PATCH",{id:t.id,dueDate:d.toISOString().slice(0,10)});toast.success("Passado para amanhã");load()}catch{toast.error("Não foi possível reagendar")}}
  const nav=[{id:"today",label:"Hoje",icon:LayoutDashboard},{id:"inbox",label:"Caixa de entrada",icon:Inbox},{id:"week",label:"Minha semana",icon:CalendarDays},{id:"progress",label:"Progresso",icon:TrendingUp}];
  return <div className="flow-shell">
    <aside className="flow-sidebar"><div className="flow-brand"><span>F</span><b>FJP <i>Flow</i></b></div><nav>{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><n.icon/> {n.label}{n.id==="inbox"&&<em>{tasks.filter(t=>!t.done).length}</em>}</button>)}</nav><div className="flow-tip"><Sparkles/><div><b>Dica do Flow</b><p>Planeje apenas 70% do tempo. Deixe espaço para o inesperado.</p></div></div><div className="flow-user"><CircleUserRound/><div><b>{user.name}</b><small>{user.email}</small></div><a href="/signout-with-chatgpt?return_to=/" title="Sair"><LogOut/></a></div></aside>
    <main className="flow-main"><header><div><p>{new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</p><h1>{view==="today"?"Sua rota de hoje":view==="inbox"?"Caixa de entrada":view==="week"?"Mapa da semana":"Seu progresso"}</h1></div><div className="header-actions"><span className="sync-pill"><span/> Sincronizado</span><Button className="flow-primary" onClick={()=>{setEditing(null);setDraft(emptyDraft());setModal(true)}}><Plus/> Novo afazer</Button></div></header>
    {loading?<div className="loading"><Loader2 className="animate-spin"/> Sincronizando sua rota...</div>:<>
      {view==="today"&&<><section className="hero-card"><div className="score"><b>{pct}%</b><Progress value={pct}/></div><div><span>ROTA DO DIA</span><h2>{doneToday.length?"Você já colocou o dia em movimento.":"Vamos colocar o dia em movimento?"}</h2><p>{doneToday.length} concluída(s) hoje · {todayTasks.length} em aberto</p></div><div className="hero-time"><b>{todayTasks.reduce((s,t)=>s+t.duration,0)} min</b><small>planejados</small></div></section><div className="flow-grid"><section className="flow-panel"><div className="panel-title"><div><span>SEQUÊNCIA SUGERIDA</span><h2>Próximos passos</h2></div><Target/></div><div className="task-tools"><label><Search/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar afazer"/></label><NativeSelect value={filter} onChange={e=>setFilter(e.target.value)}><NativeSelectOption value="all">Todas</NativeSelectOption><NativeSelectOption value="urgent">Urgentes</NativeSelectOption><NativeSelectOption value="overdue">Atrasadas</NativeSelectOption><NativeSelectOption value="quick">Até 20 min</NativeSelectOption></NativeSelect></div><TaskList tasks={todayTasks} toggle={toggle} edit={edit} remove={remove} tomorrow={tomorrow}/></section><aside className="now-panel"><span>AGORA</span>{todayTasks[0]?<><h2>{todayTasks[0].title}</h2><p><Clock3/> {todayTasks[0].duration} minutos · {todayTasks[0].energy==="high"?"energia alta":todayTasks[0].energy==="low"?"energia baixa":"energia média"}</p><div className="first-step"><b>PRIMEIRO PASSO</b>{todayTasks[0].guide||tipFor(todayTasks[0].title,todayTasks[0].category)}</div><Button className="flow-primary" onClick={()=>edit(todayTasks[0])}>Ver tarefa <ChevronRight/></Button></>:<div className="empty"><Check/><h3>Rota livre</h3><p>Adicione um afazer para começar.</p></div>}</aside></div></>}
      {view==="inbox"&&<section className="flow-panel wide"><div className="panel-title"><div><span>TODOS OS AFAZERES</span><h2>Organize o que está na sua cabeça</h2></div></div><TaskList tasks={tasks.filter(t=>!t.done)} toggle={toggle} edit={edit} remove={remove} tomorrow={tomorrow}/></section>}
      {view==="week"&&<Week tasks={tasks.filter(t=>!t.done)}/>}
      {view==="progress"&&<ProgressView tasks={tasks}/>}</>}
    </main><nav className="mobile-nav">{nav.map(n=><button key={n.id} className={view===n.id?"active":""} onClick={()=>setView(n.id)}><n.icon/><small>{n.label}</small></button>)}</nav>
    <Dialog open={modal} onOpenChange={setModal}><DialogContent className="task-dialog"><DialogHeader><DialogTitle>{editing?"Ajuste sua rota":"O que precisa sair do papel?"}</DialogTitle><DialogDescription>As alterações serão sincronizadas em seus dispositivos.</DialogDescription></DialogHeader><div className="form-grid"><Field label="Tarefa" wide><Input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Ex.: Atualizar o dashboard"/></Field><Field label="Data"><Input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></Field><Field label="Horário"><Input type="time" value={draft.dueTime||""} onChange={e=>setDraft({...draft,dueTime:e.target.value})}/></Field><SelectField label="Duração" value={String(draft.duration)} onChange={v=>setDraft({...draft,duration:Number(v)})} options={[["10","10 minutos"],["20","20 minutos"],["30","30 minutos"],["45","45 minutos"],["60","1 hora"]]}/><SelectField label="Prioridade" value={draft.priority} onChange={v=>setDraft({...draft,priority:v})} options={[["normal","Normal"],["important","Importante"],["urgent","Urgente"]]}/><SelectField label="Categoria" value={draft.category} onChange={v=>setDraft({...draft,category:v})} options={[["Trabalho","Trabalho"],["Pessoal","Pessoal"],["Estudo","Estudo"],["Saúde","Saúde"],["Casa","Casa"]]}/><SelectField label="Energia" value={draft.energy} onChange={v=>setDraft({...draft,energy:v})} options={[["low","Baixa"],["medium","Média"],["high","Alta"]]}/><SelectField label="Repetição" value={draft.repeat} onChange={v=>setDraft({...draft,repeat:v})} options={[["none","Não repetir"],["daily","Todos os dias"],["weekly","Toda semana"],["monthly","Todo mês"]]}/><Field label="Como realizar" wide><Textarea value={draft.guide} onChange={e=>setDraft({...draft,guide:e.target.value})} placeholder="Deixe vazio para receber uma sugestão do Flow."/></Field><label className="reminder"><Checkbox checked={Boolean(draft.reminder)} onCheckedChange={v=>setDraft({...draft,reminder:Boolean(v)})}/><Bell/> Avisar antes da tarefa</label></div><DialogFooter><Button variant="ghost" onClick={()=>setModal(false)}>Cancelar</Button><Button className="flow-primary" disabled={saving} onClick={saveTask}>{saving&&<Loader2 className="animate-spin"/>}{editing?"Salvar alterações":"Adicionar à rota"}</Button></DialogFooter></DialogContent></Dialog><Toaster richColors position="bottom-right"/>
  </div>
}

function Field({label,wide,children}:{label:string;wide?:boolean;children:ReactNode}){return <div className={wide?"field wide":"field"}><Label>{label}</Label>{children}</div>}
function SelectField({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[][]}){return <Field label={label}><NativeSelect className="w-full" value={value} onChange={e=>onChange(e.target.value)}>{options.map(o=><NativeSelectOption key={o[0]} value={o[0]}>{o[1]}</NativeSelectOption>)}</NativeSelect></Field>}
function TaskList({tasks,toggle,edit,remove,tomorrow}:{tasks:Task[];toggle:(t:Task)=>void;edit:(t:Task)=>void;remove:(id:string)=>void;tomorrow:(t:Task)=>void}){if(!tasks.length)return <div className="empty"><Check/><h3>Nada por aqui</h3><p>Sua rota está livre neste momento.</p></div>;return <div className="task-list">{tasks.map(t=><article className={`task ${t.priority}`} key={t.id}><Checkbox checked={Boolean(t.done)} onCheckedChange={()=>toggle(t)}/><div><b>{t.title}</b><p><span>{t.category}</span><span className={isOverdue(t)?"late":""}>{isOverdue(t)?"Atrasada · ":""}{ptDate(t.dueDate)} {t.dueTime&&`· ${t.dueTime}`}</span><span>{t.duration} min</span>{t.repeat!=="none"&&<span>↻ recorrente</span>}</p></div><div className="task-actions">{!t.done&&<Button size="xs" variant="secondary" onClick={()=>tomorrow(t)}>Amanhã</Button>}<Button size="icon-xs" variant="ghost" onClick={()=>edit(t)} title="Editar"><Edit3/></Button><Button size="icon-xs" variant="ghost" onClick={()=>remove(t.id)} title="Excluir"><Trash2/></Button></div></article>)}</div>}
function Week({tasks}:{tasks:Task[]}){const start=new Date();start.setDate(start.getDate()-((start.getDay()+6)%7));return <div className="week-grid">{Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const iso=d.toISOString().slice(0,10);const day=tasks.filter(t=>t.dueDate===iso);return <section key={iso} className={iso===new Date().toISOString().slice(0,10)?"today-col":""}><b>{d.toLocaleDateString("pt-BR",{weekday:"short"}).toUpperCase()}</b><small>{d.getDate()} {d.toLocaleDateString("pt-BR",{month:"short"})}</small>{day.map(t=><div className="week-task" key={t.id}><b>{t.title}</b><small>{t.dueTime||"Livre"} · {t.duration} min</small></div>)}{!day.length&&<p>Dia livre</p>}</section>})}</div>}
function ProgressView({tasks}:{tasks:Task[]}){const done=tasks.filter(t=>t.done);return <><div className="stats"><article><span>Concluídas</span><b>{done.length}</b><small>tarefas finalizadas</small></article><article><span>Em andamento</span><b>{tasks.length-done.length}</b><small>na sua rota</small></article><article><span>Taxa de conclusão</span><b>{tasks.length?Math.round(done.length/tasks.length*100):0}%</b><small>do total cadastrado</small></article></div><section className="flow-panel wide"><div className="panel-title"><div><span>CONQUISTAS</span><h2>O que você já tirou do caminho</h2></div><Zap/></div><div className="task-list">{done.map(t=><article className="task done" key={t.id}><Check/><div><b>{t.title}</b><p><span>{t.category}</span><span>{ptDate(t.dueDate)}</span></p></div></article>)}</div></section></>}
